name:                chordMapper
version:             0.1.0.0
github:              "githubuser/chordMapper"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/chordMapper#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- Euterpea
- random
- mtl
- PortMidi
- deepseq
- HCodecs
- stm
- time
- containers
- text
- text-show
- lens
- dhall
- filepath
- directory
- brick
- microlens
- microlens-th
- microlens-mtl
- vty
- vector

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -j4

library:
  source-dirs: src

executables:
  chordMapper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chordMapper

tests:
  chordMapper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chordMapper
    - hspec
    - QuickCheck
